name: Graham Pavey
favicon: null
layout_spectrum: 0.490360481897369
typography_spectrum: 0.22545664943754673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7591855144128203
  lightness: 0.8692436653655022
  saturation: 0.7321380607318133
  rhythmicContrast: 0.7108094289433211
purpose: []
